### ISSUE TITLE
Motive data not received

### ISSUE THREAD

**Issue by pthinesh** [whoenig/NatNetSDKCrossplatform#2]
Hi, 
when executing ./mcr <IP-where-motive-is-running>, I received the following error message.
![Screenshot from 2021-05-14 21-24-28](https://user-images.githubusercontent.com/84022671/118270365-edd64b80-b4fa-11eb-96ba-bdbea3ec1ed3.png)

This is my Motive streaming settings
![Capture](https://user-images.githubusercontent.com/84022671/118270377-f464c300-b4fa-11eb-9045-5edb18fda61b.PNG)

I am using Ubuntu 20.04
Ubuntu and Windows are connected using an Ethernet cable.

**Comment by whoenig** [comment]
This seems to be triggered when trying to join the multicast interface. Perhaps your DHCP is not working, see https://stackoverflow.com/questions/10137925/boost-asio-throws-no-such-device-exception-when-trying-to-join-multicast-group?

**Comment by pthinesh** [comment]
Thank you very much @whoenig. Problem solved.

**Comment by pthinesh** [comment]
Thank you very much @whoenig. Problem solved.
