### ISSUE TITLE
Request for help in using UNIX time in Natnet SampleClient.cpp

### ISSUE THREAD

**Issue by gauricollab09** [whoenig/NatNetSDKCrossplatform#4]
My question is regarding Optitrack - Motive and NatNet SDK SampleClient.cpp script.

My goal is to capture the "time now" in UNIX on my NatNet machine, which is running on Ubuntu.

However, I’m having trouble figuring out where exactly to implement this in the SampleClient.cpp code. I’ve already added the following line using std::chrono to capture the current time in the Data handler:

const auto now = std::chrono::system_clock::now();
const std::time_t t_c = std::chrono::system_clock::to_time_t(now);
![image (1)](https://github.com/user-attachments/assets/b871f52d-b021-4681-90cb-8bd887178328)

But I’m unsure if this should be placed inside the void NATNET_CALLCONV DataHandler(sFrameOfMocapData* data, void* pUserData) function or elsewhere. I also want to use the time_now in the OutputFrameQueueToConsole() function where the latencies, etc are printed, but I’m a bit confused on how to approach this since I’m not very comfortable with C++ code. (Running into errors accessing the variables etc)

printf("Server Timestamp : %s\n", std::ctime(&t_c)); 
![image (2)](https://github.com/user-attachments/assets/2b2e15f4-f6a4-404b-8607-d2c80b9e2b09)

Could you provide some guidance on where this logic should go? Thank you so much for your help.

**Comment by whoenig** [comment]
NatNet and the SimpleClient example are actually from OptiTrack (the vendor). I only host the code here for version control and to include minimal changes to be able to compile on Linux.

Perhaps you can explain your goal in https://github.com/IMRCLab/libmotioncapture, where I maintain the user code base.

**Comment by gauricollab09** [comment]
Hi @whoenig, Thank you for your reply.
